version: "3.8"
services:
  backend:
    build: ./Backend/
    restart: unless-stopped
    environment:
      - AZURE_OPENAI_CHATGPT_DEPLOYMENT=${AZURE_OPENAI_CHATGPT_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '8080:8080'
  frontend:
    build: 
      context: ./Frontend/
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - "backend"
